print('Please enter the first number to add:')
fst = input()
print('Please enter the second number to add:')
snd = input()
print('Please enter the third number to add:')
trd = input()
sum = int(fst) + int(snd) + int(trd)
print('Your sum is ' + fst + snd + trd)
print('jk ' + str(sum))
